# Use a small image for Radicale
FROM python:3.9-alpine

ARG VERSION=master
ARG DEPENDENCIES=bcrypt

# Install dependencies and Radicale
RUN apk add --no-cache gcc libffi-dev musl-dev ca-certificates openssl \
    && python -m venv /app/venv \
    && /app/venv/bin/pip install --no-cache-dir "Radicale[${DEPENDENCIES}] @ https://github.com/Kozea/Radicale/archive/${VERSION}.tar.gz"

# Volumes for config and data
VOLUME /var/lib/radicale /config

# Expose Radicale port
EXPOSE 5232

# Run Radicale
CMD ["/app/venv/bin/python", "/app/venv/bin/radicale", "--hosts", "0.0.0.0:5232"]
