apiVersion: v1
kind: Pod
metadata:
  name: pvc-check
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: config-storage
      mountPath: /config
  volumes:
  - name: config-storage
    persistentVolumeClaim:
      claimName: config-pvc
