apiVersion: v1
kind: PersistentVolume
metadata:
  name: radicale-pv
  labels:
    type: local
spec:
  storageClassName: "radicale"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/radicale # This is the path on the host where the data will be stored
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain