apiVersion: v1
kind: Service
metadata:
  name: radicale-service-latest
  labels:
    app: radicale
    version: latest
spec:
  type: LoadBalancer
  selector:
    app: radicale
    version: latest
  ports:
  - protocol: TCP
    port: 80          # External port for latest version
    targetPort: 5232  # Internal port in the container
---
apiVersion: v1
kind: Service
metadata:
  name: radicale-service-stable
  labels:
    app: radicale
    version: stable
spec:
  type: LoadBalancer
  selector:
    app: radicale
    version: stable
  ports:
  - protocol: TCP
    port: 90          # External port for stable version
    targetPort: 5232  # Internal port in the container
---
apiVersion: v1
kind: Service
metadata:
  name: radicale-service-test
  labels:
    app: radicale
    version: test
spec:
  type: LoadBalancer
  selector:
    app: radicale
    version: test
  ports:
  - protocol: TCP
    port: 100         # External port for test version
    targetPort: 5232  # Internal port in the container
